server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: miningW0rld
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          api-client-oidc:
            provider: spring
            # the client id and secret are generated when client-app registers with oauth provider
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://oauth-client-app:8080/login/oauth2/code/{registrationId}"
            # openid is the authentication plugin on top of oauth2 protocol
            scope: openid
            client-name: api-client-oidc
          api-client-authorization-code:
            provider: spring
            # the client id and secret are generated when client-app registers with oauth provider
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://oauth-client-app:8080/authorized"
            scope: api.read
            client-name: api-client-authorization-code
        provider:
          spring:
            # issuer is the authorization server
            issuer-uri: http://provider-oauth-auth-server:9000