name: Build
# on what events should github trigger the build workflow?
# in this case when code is pushed to any branch
on:
  push:
    branches: [ "**" ] # Note: `*`regex  matches all characters except '/'
                       #       `**` regex matches any branch on the repository

jobs:
  build-bookmarker-api:         # JOB-1: build bookmarker API
    name: Build bookmarker-api
    runs-on: ubuntu-latest      # you can pin the version as well like ubuntu-20.04
    defaults:
      run:
        working-directory: ./bookmarker-api # run the steps in this working directory
    steps:
      - name: Checkout repository    # step1: clone the bookmarker-app repository from github?
        uses: actions/checkout@v3

      - name: Set up JDK 17          # step2: setup jdk17 distributed by temurin with maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'         # use java 17 version
          distribution: 'temurin'    # for aws -> amazon-correto & for azure -> microsoft distribution can be set
          cache: maven

      - name: Build with Maven       # step3: build with maven
        run: ./mvnw verify

      # conditional execution
      - if:  github.ref == 'refs/heads/master'  # execute this step only when the code is pushed on master branch
        name: Build and publish Docker Image    # step4: build and push docker images
        run: |
          ./mvnw clean package jib:dockerBuild -DskipTests
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmarker-api
  

  build-bookmarker-ui:                # JOB-2: build bookmarker UI
    name: Build bookmarker-ui
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmarker-ui-nextjs
    steps:
      - name: Checkout repository     # step1: clone the bookmarker-app repository from github?
        uses: actions/checkout@v3

      - name: Setup Node.js 16        # step2: setup node.js 16 with yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: bookmarker-ui-nextjs/yarn.lock

      - name: Install dependencies    # step3: install dependencies
        run: yarn

      - name: Build                   # step4: build
        run: yarn build

      - if: github.ref == 'refs/heads/master'  # step5: changes on master get built & pushed to dockerhub
        name: Build and Publish Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bookmarker-ui-nextjs .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmarker-ui-nextjs
          

# suggested by github build.yml template:
#
# Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#- name: Update dependency graph
#  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
